apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: jenkins-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
